name: catalog
on:
  push:
    paths-ignore:
    - '.catalog/**'
    - '_layouts/**'
    - '.github/**'
    - 'package.json'
    - 'package-lock.json'

jobs:
  mkcatalog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm run mkcatalog
      run: |
        npm install
        npm run mkcatalog
        git config --global user.email "gugegev5@gmail.com" && git config --global user.name "actions:catalog"
        git add -A
        if [[ $(echo $(git status|grep 'nothing to commit')) -eq '' ]];
        then git commit -m "[Actions: catalog] Catalog Update"; 
        git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/"$GITHUB_REPOSITORY HEAD:master;
        else echo 'catalog has not changed';
        fi
        
